import bcrypt from 'bcryptjs';
const  data = {
        users: [
                {
                        name:'Deekshant',
                        email:'admin@example.com',
                        password: bcrypt.hashSync('123456',8),
                        isAdmin: true,
                },
                {
                        name:'Parth',
                        email:'user@example.com',
                        password: bcrypt.hashSync('123456',8),
                        isAdmin: false,
                }
        ],
  products:[
    {
      _id:'1',
      name:'nike slim shirt',
      category:'Shirts',
      image:'/images/p1.jpg',
      price: 150,
      countInStock:10,
      Brand: 'Nike',
      ratings: 4.5,
      numReviews:10,
      Description:'high Quality Products',
    },
    {
      _id:'2',
      name:'nike slim shirt',
      category:'Shirts',
      image:'/images/p2.jpg',
      price: 150,
      countInStock:10,
      Brand: 'Nike',
      ratings: 4.5,
      numReviews:10,
      Description:'high Quality Products',
    },
    {
      _id:'3',
      name:'nike slim shirt',
      category:'Shirts',
      image:'/images/p3.jpg',
      price: 150,
      countInStock:20,
      Brand: 'Nike',
      ratings: 4.5,
      numReviews:10,
      Description:'high Quality Products',
    },
    {
      _id:'4',
      name:'nike slim shirt',
      category:'Shirts',
      image:'/images/p4.jpg',
      price: 150,
      countInStock:0,
      Brand: 'Nike',
      ratings: 4.5,
      numReviews:10,
      Description:'high Quality Products',
    },
    {
      _id:'5',
      name:'nike slim shirt',
      category:'Shirts',
      image:'/images/p5.jpg',
      price: 150,
      countInStock:15,
      Brand: 'Nike',
      ratings: 4.5,
      numReviews:10,
      Description:'high Quality Products',
    },
    {
      _id:'6',
      name:'nike slim shirt',
      category:'Shirts',
      image:'/images/p6.jpg',
      price: 150,
      countInStock:12,
      Brand: 'Nike',
      ratings: 4.5,
      numReviews:10,
      Description:'high Quality Products',
    },
  ],
};


export default data;
